[package]
name = "hecate-vm"
version = "0.14.2"
edition = "2024"
description = "The main package for the hecate vm"
license-file = "LICENSE"
repository = "https://github.com/hecate-vm/hecate-vm"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.95"
base64 = "0.22"
clap = { version = "4.5.22", features = ["derive"] }
rvsim = { git = "https://github.com/hecate-vm/rvsim", version = "0.2.2", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tiny_http = "0.12"
toml = "0.8"
tungstenite = "0.24"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

[features]
default = ["rv32c", "rv32fd", "demo"]
rv32c = ["rvsim/rv32c"]
rv32fd = ["rvsim/rv32fd"]
demo = ["hello_world", "linked_list", "vector_contiguous"]
all_examples = ["hello_world", "linked_list", "rust_hello", "vector_contiguous"]
hello_world = []
linked_list = []
rust_hello = []
vector_contiguous = []
http_control_api = []
