set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET riscv32-unknown-elf)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
